### ISSUE TITLE
No Images Match "pytorch-efa01"

### ISSUE THREAD

**Issue by verbiiz** [yaroslavvb/imagenet18#9]
Running the main script command:

```
python train.py
```

I get:

```
Exception are  [AssertionError('No images match pytorch-efa01 in us-west-2, check name and image permissions')]
Traceback (most recent call last):
  File "train.py", line 453, in <module>
    main()
  File "train.py", line 305, in main
    job = ncluster.make_job(name=args.name,
  File "/usr/local/lib/python3.8/site-packages/ncluster/aws_backend.py", line 1294, in make_job
    raise exceptions[0]
  File "/usr/local/lib/python3.8/site-packages/ncluster/aws_backend.py", line 1268, in make_task_fn
    tasks[i] = make_task(f"{i}.{name}", run_name=run_name,
  File "/usr/local/lib/python3.8/site-packages/ncluster/aws_backend.py", line 1070, in make_task
    image = u.lookup_image(image_name)
  File "/usr/local/lib/python3.8/site-packages/ncluster/aws_util.py", line 397, in lookup_image
    assert len(images) > 0, f"No images match {str(wildcard)} in {get_region()}, check name and image permissions"
AssertionError: No images match pytorch-efa01 in us-west-2, check name and image permissions

> /usr/local/lib/python3.8/site-packages/ncluster/aws_util.py(397)lookup_image()
-> assert len(images) > 0, f"No images match {str(wildcard)} in {get_region()}, check name and image permissions"
```

I have set up the snapshots & created volumes from them using the scripts provided.

**Comment by verbiiz** [comment]
Is there an extra setup for using an image? I'm using zone us-west-2a, in your README you reference us-east-1, maybe this is the only region where the AMI you reference (pytorch-eaf01) exists?
